## Lesson 2
# Numpy

In [1]:
# import libraries
import numpy as np

In [5]:
# Numpy Basic Array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# DataType in Numpy

a.dtype

dtype('int64')

In [7]:
# Assigning the DataType in Numpy

a = np.array([1,2,3], dtype='int16')
print(a)
a.dtype

[1 2 3]


dtype('int16')

In [17]:
# Convert float into integer and also have 2D array

b = np.array([[9.0, 8.5, 7.0] , [6.0, 5.0, 4.0]], dtype='int16')
print(b)
print("===================================")
print(b.dtype)
print("===================================")
print(b.ndim)
print("===================================")
print(b.shape)
print("===================================")
print(b.itemsize)

[[9 8 7]
 [6 5 4]]
int16
2
(2, 3)
2


In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype='int16')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
b[0,1,1]

np.int16(4)

In [26]:
# Replace multiple numbers
b[:,1,:]=[[9,9],[10,10]]
print(b)

[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


In [31]:
# Making 3D array of 2*3 all with number 0

c = np.zeros((2,3), dtype='int16')
print(c, c.dtype)


[[0 0 0]
 [0 0 0]] int16


In [32]:
# Making 3D array of 2*3 all with number 1 

c = np.ones((2,3), dtype='int16')
print(c, c.dtype)

[[1 1 1]
 [1 1 1]] int16


In [34]:
c = np.full((2,3), 55, dtype='int16')
print(c, c.dtype)

[[55 55 55]
 [55 55 55]] int16


In [35]:
c = np.full(b.shape, 16, dtype='int16')
print(c)

[[[16 16]
  [16 16]]

 [[16 16]
  [16 16]]]


In [39]:
# Creating a random numbers

c = np.random.rand(4,2)
print(c)

[[0.60042923 0.82148804]
 [0.40723114 0.42191709]
 [0.92940314 0.64745146]
 [0.07889914 0.6297907 ]]


In [43]:
# Creating a random numbers in a range and just int

np.random.randint(-100000,999999, size=(b.shape))

array([[[625532, -50845],
        [787609,  52262]],

       [[106263, 882361],
        [129414, 464489]]], dtype=int32)

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# Repeating array

arr = np.array([[1,2,3]])
print(arr)

print("===================================")

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
# Substituting single number in an array

z = np.zeros((3,3), dtype='int16')
print(z)

print("===================================")
z[1,1] = 9
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [51]:
# Array inside array
out = np.ones((5,5), dtype='int16')
print(out)

print("===================================")

out[1:-1, 1:-1] = z
print(out)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [53]:
# Copy the number is array
a = np.array([1,2,3])
b= a.copy()
print(b)
print("===================================")
b[0]=100

print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]


In [57]:
# Power of arithmetic equation in arrays
a = np.array([1,2,3,4])
print(a+2)
print("===================================")
print(a-2)
print("===================================")
print(a*2)
print("===================================")
print(a/2)
print("===================================")
print(a**2)
print("===================================")

b = np.array([1,0,1,0])
print(a+b)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 2 4 4]


In [60]:
# Geometric equations in arrays using Numpy
sin = np.sin(a)
cos = np.cos(a)
print(sin)
print(cos)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### For more Numpy mathematic functions and equations please refer to the following link:
https://numpy.org/doc/stable/reference/routines.math.html

In [63]:
# Working with arrays with different x and y

a = np.ones((2,3))
print(a)
print("===================================")
b = np.full((3,2),2)
print(b)
print("===================================")
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

## Statistics

In [64]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)


[[1 2 3]
 [4 5 6]]


In [65]:
# Different statistics
amin = np.min(stats)
amax = np.max(stats, axis=1)
asum = np.sum(stats)
asumaxis = np.sum(stats, axis=0)
print(amin)
print(amax)
print(asum)
print(asumaxis)

1
[3 6]
21
[5 7 9]


In [67]:
# Reshaping arrays using Numpy
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

print("===================================")

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
# Vertical stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(v1)
print(v2)

print("===================================")

vstack = np.vstack([v1,v2,v1,v2])
print(vstack)

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [70]:
# Horizontal stacking
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
print(h1)
print(h2)

print("===================================")

hstack = np.hstack([h1,h2,h1,h2])
print(hstack)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [ ]:
file_data