## Lesson 2
# Numpy

In [1]:
# import libraries
import numpy as np

In [5]:
# Numpy Basic Array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# DataType in Numpy

a.dtype

dtype('int64')

In [7]:
# Assigning the DataType in Numpy

a = np.array([1,2,3], dtype='int16')
print(a)
a.dtype

[1 2 3]


dtype('int16')

In [17]:
# Convert float into integer and also have 2D array

b = np.array([[9.0, 8.5, 7.0] , [6.0, 5.0, 4.0]], dtype='int16')
print(b)
print("===================================")
print(b.dtype)
print("===================================")
print(b.ndim)
print("===================================")
print(b.shape)
print("===================================")
print(b.itemsize)

[[9 8 7]
 [6 5 4]]
int16
2
(2, 3)
2


In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype='int16')
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
b[0,1,1]

np.int16(4)

In [26]:
# Replace multiple numbers
b[:,1,:]=[[9,9],[10,10]]
print(b)

[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


In [31]:
# Making 3D array of 2*3 all with number 0

c = np.zeros((2,3), dtype='int16')
print(c, c.dtype)


[[0 0 0]
 [0 0 0]] int16


In [32]:
# Making 3D array of 2*3 all with number 1 

c = np.ones((2,3), dtype='int16')
print(c, c.dtype)

[[1 1 1]
 [1 1 1]] int16


In [34]:
c = np.full((2,3), 55, dtype='int16')
print(c, c.dtype)

[[55 55 55]
 [55 55 55]] int16


In [35]:
c = np.full(b.shape, 16, dtype='int16')
print(c)

[[[16 16]
  [16 16]]

 [[16 16]
  [16 16]]]


In [39]:
# Creating a random numbers

c = np.random.rand(4,2)
print(c)

[[0.60042923 0.82148804]
 [0.40723114 0.42191709]
 [0.92940314 0.64745146]
 [0.07889914 0.6297907 ]]


In [43]:
# Creating a random numbers in a range and just int

np.random.randint(-100000,999999, size=(b.shape))

array([[[625532, -50845],
        [787609,  52262]],

       [[106263, 882361],
        [129414, 464489]]], dtype=int32)

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# Repeating array

arr = np.array([[1,2,3]])
print(arr)

print("===================================")

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
# Substituting single number in an array

z = np.zeros((3,3), dtype='int16')
print(z)

print("===================================")
z[1,1] = 9
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [51]:
# Array inside array
out = np.ones((5,5), dtype='int16')
print(out)

print("===================================")

out[1:-1, 1:-1] = z
print(out)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
